kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
  apiServerAddress: 127.0.0.1
nodes:
  - role: control-plane
    image: kindest/node:v.133.1
  - role: worker
    image: kindest/node:v.133.1
  - role: worker
    image: kindest/node:v.133.1

